### ISSUE TITLE
Burger menu

### ISSUE THREAD

**Issue by grage03** [grage03/prello#84]
![image](https://user-images.githubusercontent.com/68416825/160487386-f68d9c0a-93a6-49a3-81a2-878499ce4b34.png)

The menu should contain the main items from the header, the authorization button can be left in place.

**Comment by mrpie228** [comment]
slyles
/assign @Kissa41

**Comment by mrpie228** [comment]
only design

**Comment by grage03** [comment]
Icons and colors can be found here - https://www.figma.com/file/4vcQLHFPR6czUBdgqmxCQq/MbilePrello?node-id=0%3A1
